// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkr4_UJSftcVt5M27JgWxuow7Pj3tpVI',
    appId: '1:141546345148:web:263ad762d26de60d4d36b9',
    messagingSenderId: '141546345148',
    projectId: 'crud-tutorial-devbruno',
    authDomain: 'crud-tutorial-devbruno.firebaseapp.com',
    storageBucket: 'crud-tutorial-devbruno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUdRTINPTxJ0Do0R080OIua_AOUxksFo',
    appId: '1:141546345148:android:d711156420bcc6384d36b9',
    messagingSenderId: '141546345148',
    projectId: 'crud-tutorial-devbruno',
    storageBucket: 'crud-tutorial-devbruno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhesmIC3ZJWTDCp9O4TnsX2NDFR3cB2Ig',
    appId: '1:141546345148:ios:b9d1fcd5d31785044d36b9',
    messagingSenderId: '141546345148',
    projectId: 'crud-tutorial-devbruno',
    storageBucket: 'crud-tutorial-devbruno.appspot.com',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhesmIC3ZJWTDCp9O4TnsX2NDFR3cB2Ig',
    appId: '1:141546345148:ios:b9d1fcd5d31785044d36b9',
    messagingSenderId: '141546345148',
    projectId: 'crud-tutorial-devbruno',
    storageBucket: 'crud-tutorial-devbruno.appspot.com',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkr4_UJSftcVt5M27JgWxuow7Pj3tpVI',
    appId: '1:141546345148:web:8f1742fdfd83bd714d36b9',
    messagingSenderId: '141546345148',
    projectId: 'crud-tutorial-devbruno',
    authDomain: 'crud-tutorial-devbruno.firebaseapp.com',
    storageBucket: 'crud-tutorial-devbruno.appspot.com',
  );
}
